name: "Generate gh-pages"
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '*/10 * * * *'  # every 10th minute

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        fetch-depth: 0
    - name: Install nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: update
      run: |
        nix run
        git config --local user.name "github-actions[bot]"
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        git commit -m "auto update - $(date --rfc-3339=seconds)" \
          && git push --set-upstream origin gh-pages \
          || true
